### ISSUE TITLE
Not converting temp files after successful download

### ISSUE THREAD

**Issue by NareshKumarSuruvu** [sgrebnov/cordova-plugin-background-download#19] opened 2016-01-29 14:36 UTC
There are two situations when this is happening:
- I get an error saying "Cannot copy from temporary path to actual path" 
- No errors at all are shown. However, the file shows 0 MB. When checked in the filemanager, we see that there are two files, eg, abc.mp3 and abc.mp3.temp. The abc.mp3 file has 0 MB, while the actual download has happened to the temp file. For some reason, we feel the function copyTempFileToActualFile is not called. Wanted to know what scenarios can this happen.

We need to handle both these scenarios as our mobile app on android is not able to play the music file that it downloaded. This issue is not consistently happening. We feel there is a possibility of network speed or something causing it to happen sometimes. Please advise on help to handle these issues.

Thanks & Regards,
Naresh.

**Comment by sgrebnov** [comment] 2016-02-03 09:00
Going to review pending PRs and issues today, do you have code snippet I can use to repro this issue? Also, what Android version do you use?

**Comment by NickToropov** [comment] 2018-06-20 08:13
Hi @NareshKumarSuruvu, we've made a number of improvements recently. Please try to update plugin and check if the issue gone.

I'll close it for now but please feel free to reopen it if the issue is still actual for you.

**Closed by NickToropov** 2018-06-20 08:13 UTC
