### ISSUE TITLE
Crash upon download completion

### ISSUE THREAD

**Issue by darthdie** [sgrebnov/cordova-plugin-background-download#8] opened 2015-04-01 21:16 UTC
Hey there.

For some reason on Android once a download finishes the plugin (and consequently my app) crashes. Using adb logcat I was able to pull together a stack trace (and find that it's because of a NullPointerException), but unfortunately I'm not super familiar with the Android API and so I was hoping you'd be able to provide some help?

```
E/AndroidRuntime(18302): Process: com.ionicframework.myapp201347, PID: 18302

E/AndroidRuntime(18302): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.ionicframework.myapp201347 (has extras) } in org.apache.cordova.backgroundDownload.BackgroundDownload$2@42b63d10

E/AndroidRuntime(18302):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:782)

E/AndroidRuntime(18302):    at android.os.Handler.handleCallback(Handler.java:733)

E/AndroidRuntime(18302):    at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(18302):    at android.os.Looper.loop(Looper.java:157)

E/AndroidRuntime(18302):    at android.app.ActivityThread.main(ActivityThread.java:5293)

E/AndroidRuntime(18302):    at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime(18302):    at java.lang.reflect.Method.invoke(Method.java:515)

E/AndroidRuntime(18302):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)

E/AndroidRuntime(18302):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

E/AndroidRuntime(18302):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

E/AndroidRuntime(18302):    at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime(18302): Caused by: java.lang.NullPointerException

E/AndroidRuntime(18302):    at org.apache.cordova.backgroundDownload.BackgroundDownload.CleanUp(BackgroundDownload.java:236)

E/AndroidRuntime(18302):    at org.apache.cordova.backgroundDownload.BackgroundDownload.access$100(BackgroundDownload.java:46)

E/AndroidRuntime(18302):    at org.apache.cordova.backgroundDownload.BackgroundDownload$2.onReceive(BackgroundDownload.java:385)

E/AndroidRuntime(18302):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:772)
```

**Comment by geekyguy18** [comment] 2017-01-27 19:40
@darthdie any update on this issue, did u fixed it?

@sgrebnov org.apache.cordova.backgroundDownload.BackgroundDownload.CleanUp - line:234 
causing crashing app on download completion, as i am not an Android developer so i can't fix it my own, if anyone have any knowledge of this issue please help us to fix it.

**Comment by NickToropov** [comment] 2018-06-20 08:17
Hi guys! We've made a number of improvements recently. Please try to update plugin an check if the issue has gone.
I'll close it for now but feel free to reopen it if the issue is still actual for you.

**Closed by NickToropov** 2018-06-20 08:17 UTC
